### ISSUE TITLE
Need support and instructions for one physical gateway forwarding traffic to multiple miners

### ISSUE THREAD

**Issue by simeononsecurity** [Carniverous19/helium-DIY-middleman#4]
I'd like to see support for one running multiple instances of the virtual gateway on one machine and only having to have one LoRA Gateway forwarding traffic to the middleman and middle man being able to forward that data to multiple miners. Additionally multiple gateways one each to multiple miners.

**Comment by kissste** [comment]
I'm working on almost exactly the same thing. Multiple Lora Gateways feeding one or many miners.

**Comment by simeononsecurity** [comment]
> I'm working on almost exactly the same thing. Multiple Lora Gateways feeding one or many miners.

Well when you have something please link me

**Comment by alexevictor** [comment]
> I'm working on almost exactly the same thing. Multiple Lora Gateways feeding one or many miners.

have u any result on that?

**Comment by kissste** [comment]
It's working well. Multiple RF Lora Gateways to Multiple Miners.

**Comment by simeononsecurity** [comment]
> 

I won't say exactly how do to it. But the repos to do it are the following.
https://github.com/simeononsecurity/helium-DIY-middleman

and either
https://github.com/simeononsecurity/chirpstack-packet-multiplexer
or
https://github.com/simeononsecurity/samplicator

YMV
Good luck

**Comment by alexevictor** [comment]
in any way can work many miners 2 many miners?

**Comment by simeononsecurity** [comment]
> in any way can work many miners 2 many miners?

I'm not here for support. Give it a shot and see.

**Comment by alexevictor** [comment]
thnks anyway, only i ask

**Comment by sblanchard** [comment]
I've got this working to a point the packet forwarder logs 
 packet-forwarder  INFO: [up] PUSH_ACK received in 1 ms
 packet-forwarder  INFO: [down] PULL_ACK received in 6 ms
but the blue light (sensecap m1) turns to a fast flast meaning no connection to helium network. 
I had the same behaviour with it running on the device and also this software running on a pc.
Any ideas? @simeononsecurity  you seem to be the man. Does this still work on the new software releases?

**Comment by simeononsecurity** [comment]
> I've got this working to a point the packet forwarder logs packet-forwarder INFO: [up] PUSH_ACK received in 1 ms packet-forwarder INFO: [down] PULL_ACK received in 6 ms but the blue light (sensecap m1) turns to a fast flast meaning no connection to helium network. I had the same behaviour with it running on the device and also this software running on a pc. Any ideas? @simeononsecurity you seem to be the man. Does this still work on the new software releases?

Not here to provide support for this one.
Seems you have a configuration issue outside of the software anyways.

**Comment by sblanchard** [comment]
To answer my own question, it is gateway-config causing the problem and using a 6 month old version solved the problem

**Comment by flash008a** [comment]
@simeononsecurity , do you have the latest version of this gateways2miners.py? Or is this the latest you got on this GitHub?

**Comment by sblanchard** [comment]
@flash008a i've fiddled around with this, some problems is that most packet forwarders have the same mac address in their config - AA555A0000000000...which messes up the internal handling by mac address...the frequency/channel calculation only supports 915 which messes up the chan field on other frequencies like 868 (if you're on 915 don't worry)

it can be useful to log all messages to see if comms are happening.  
in the

if msg['_NAME_'] == messages.MsgPushData.NAME:
                self.handle_PUSH_DATA(msg, addr)
elif msg['_NAME_'] == messages.MsgPullResp.NAME:
....
`else:
     self.vgw_logger.info(f"received from {addr} {msg['_NAME_']}")
`

**Comment by flash008a** [comment]
It doesn't seem like _middleman_args="--tx-adjust 0 --rx-adjust" parameter works, either.

**Comment by flash008a** [comment]
middleman_args="--tx-adjust 0 --rx-adjust doesn't seem to work, either.

**Comment by flash008a** [comment]
middleman_args="--tx-adjust 0 --rx-adjust"  doesn't seem to work, either.

**Comment by simeononsecurity** [comment]
Please keep comments relevant to the issue on hand. Otherwise start your own issue.

**Comment by r00t3r97** [comment]
is someone made some updates for mux_enable ?

**Comment by jibjab99** [comment]
This is already how it worked? However, it is no longer working due to miner updates.

**Comment by simeononsecurity** [comment]
> This is already how it worked? However, it is no longer working due to miner updates.

It's still a powerful tool for relaying lora communications. 
Also this tool is definitely a 1:1. It can not forward to multiple miners/gateways without the help of other software.

**Comment by proxynetul** [comment]
> > This is already how it worked? However, it is no longer working due to miner updates.
> 
> It's still a powerful tool for relaying lora communications. Also this tool is definitely a 1:1. It can not forward to multiple miners/gateways without the help of other software.

Can you please fix this to work with new updates ? it no longer send beacons, wintess is ok

**Comment by simeononsecurity** [comment]
> > > This is already how it worked? However, it is no longer working due to miner updates.
> > 
> > It's still a powerful tool for relaying lora communications. Also this tool is definitely a 1:1. It can not forward to multiple miners/gateways without the help of other software.
> 
> Can you please fix this to work with new updates ? it no longer send beacons, wintess is ok

Not a developer on this project. Submit a separate issue

**Comment by proxynetul** [comment]
> > > > This is already how it worked? However, it is no longer working due to miner updates.
> > > 
> > > 
> > > It's still a powerful tool for relaying lora communications. Also this tool is definitely a 1:1. It can not forward to multiple miners/gateways without the help of other software.
> > 
> > 
> > Can you please fix this to work with new updates ? it no longer send beacons, wintess is ok
> 
> Not a developer on this project. Submit a separate issue

i know that, but probably you shoud know to that :) no one offer future update.
